--- !ditz.rubyforge.org,2008-03-06/project 
name: construct
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: construct
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: neo
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-08-18 14:58:47.209904 Z
    - Avdi Grimm <avdi@avdi.org>
    - created
    - Initial release
